"""add repo_type to analysis

Revision ID: 31b77cc98f3c
Revises: ffb8c3aa7d85
Create Date: 2026-07-22 11:11:44.410819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b77cc98f3c'
down_revision: Union[str, Sequence[str], None] = 'ffb8c3aa7d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('repo_type', sa.String(), server_default='library', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'repo_type')
    # ### end Alembic commands ###
