"""add security quality summary grade to metrics

Revision ID: ff3b1ee28354
Revises: 31b77cc98f3c
Create Date: 2026-07-24 11:45:24.148212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff3b1ee28354'
down_revision: Union[str, Sequence[str], None] = '31b77cc98f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('security_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('metrics', sa.Column('code_quality_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('metrics', sa.Column('health_grade', sa.String(length=5), server_default='C', nullable=True))
    op.add_column('metrics', sa.Column('executive_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'executive_summary')
    op.drop_column('metrics', 'health_grade')
    op.drop_column('metrics', 'code_quality_score')
    op.drop_column('metrics', 'security_score')
    # ### end Alembic commands ###
